# 02 - rust-toolchain.toml — VM-ENGINE v0
# Deterministic toolchain pin for the workspace.

[toolchain]
# Pin to an exact stable release (no toolchain drift).
channel = "1.80.0"

# Keep base install minimal; add only the components we require.
profile = "minimal"
components = ["rustfmt", "clippy"]

# If CI needs cross-OS builds, explicitly add targets (otherwise omit).
# targets = [
#   "x86_64-unknown-linux-gnu",
#   "aarch64-unknown-linux-gnu",
#   "x86_64-apple-darwin",
#   "aarch64-apple-darwin",
#   "x86_64-pc-windows-msvc",
#   "aarch64-pc-windows-msvc",
# ]
