<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta
      http-equiv="Content-Security-Policy"
      content="
        default-src 'self' asset: tauri: ipc:;
        img-src 'self' asset: data: blob:;
        style-src 'self' 'unsafe-inline';
        font-src 'self' asset: data:;
        script-src 'self';
        connect-src 'self' asset: tauri: ipc:;
        object-src 'none';
        frame-ancestors 'none';
      ">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="color-scheme" content="light dark">
    <title>VM Engine — Report Viewer</title>
    <!-- Local, bundled stylesheet (no external fonts or CDNs) -->
    <link rel="stylesheet" href="./assets/app.css">
  </head>
  <body>
    <noscript>
      This application requires JavaScript (offline, no network). Please enable it to view reports.
    </noscript>
    <!-- App root -->
    <div id="app" role="main" aria-live="polite">
      <!-- Section anchors in Doc 7 order; content injected by bundled JS from artifacts -->
      <section id="sec-cover-snapshot" data-section="cover_snapshot" aria-labelledby="h-cover">
        <h1 id="h-cover" class="visually-hidden">Cover & Snapshot</h1>
      </section>
      <section id="sec-eligibility" data-section="eligibility" aria-labelledby="h-eligibility">
        <h2 id="h-eligibility" class="visually-hidden">Eligibility & Rolls</h2>
      </section>
      <section id="sec-ballot" data-section="ballot" aria-labelledby="h-ballot">
        <h2 id="h-ballot" class="visually-hidden">Ballot Method</h2>
      </section>
      <section id="sec-allocation" data-section="allocation" aria-labelledby="h-allocation">
        <h2 id="h-allocation" class="visually-hidden">Allocation & Aggregation</h2>
      </section>
      <section id="sec-legitimacy" data-section="legitimacy_panel" aria-labelledby="h-legitimacy">
        <h2 id="h-legitimacy" class="visually-hidden">Legitimacy Panel</h2>
      </section>
      <section id="sec-outcome" data-section="outcome_label" aria-labelledby="h-outcome">
        <h2 id="h-outcome" class="visually-hidden">Outcome / Label</h2>
      </section>
      <!-- Optional map panel (only shown when a FrontierMap exists).
           data-map-style points to LOCAL style.json (no remote tiles). -->
      <section id="sec-frontier" data-section="frontier" aria-labelledby="h-frontier" hidden>
        <h2 id="h-frontier" class="visually-hidden">Frontier Map</h2>
        <div id="map"
             data-map-style="./maps/style.json"
             style="width:100%;height:420px"
             role="img"
             aria-label="Frontier map (offline)">
        </div>
      </section>
      <section id="sec-ties" data-section="ties" aria-labelledby="h-ties">
        <h2 id="h-ties" class="visually-hidden">Tie Resolution</h2>
      </section>
      <section id="sec-sensitivity" data-section="sensitivity" aria-labelledby="h-sensitivity">
        <h2 id="h-sensitivity" class="visually-hidden">Sensitivity</h2>
      </section>
      <section id="sec-integrity" data-section="integrity" aria-labelledby="h-integrity">
        <h2 id="h-integrity" class="visually-hidden">Integrity & Reproducibility</h2>
      </section>
      <footer id="fixed-footer" data-section="footer" aria-label="Fixed footer">
        <!-- Renderer writes fixed footer line with IDs from RunRecord/Result -->
      </footer>
    </div>
    <!-- Production bundle (generated by Vite). Keep relative path; no external scripts. -->
    <script type="module" src="./assets/main.js"></script>
  </body>
</html>
